"""
config/merchants.py
===================
Merchant → Category mapping for the Finance Intelligence Pipeline.

This is the "brain" of the categorizer. Every known merchant keyword
maps to a standardized category used throughout the data mart.

To add a new merchant: add an entry in the relevant category list.
Keys are case-insensitive regex patterns matched against transaction descriptions.

CATEGORIES:
    GROCERIES       - Supermarkets, food stores
    DINING          - Restaurants, cafes, fast food
    TRANSPORT       - Trains, buses, trams, fuel
    HEALTHCARE      - Pharmacies, medical
    BEAUTY          - Cosmetics, personal care
    CLOTHING        - Fashion, shoes, accessories
    ENTERTAINMENT   - Streaming, events, hobbies
    UTILITIES       - Phone, internet, bills
    RENT            - Housing payments
    ELECTRONICS     - Tech, appliances
    INCOME          - Salary, tax returns, bonuses
    TRANSFER        - Peer-to-peer, bank transfers
    SUBSCRIPTIONS   - Recurring digital services
    OTHER           - Uncategorized
"""

from typing import Dict, List

# Each key is a category name.
# Each value is a list of regex patterns (case-insensitive) to match in description.
MERCHANT_PATTERNS: Dict[str, List[str]] = {
    "GROCERIES": [
        r"biedronka",
        r"kaufland",
        r"lidl",
        r"auchan",
        r"carrefour",
        r"lewiatan",
        r"stokrotka",
        r"żabka",
        r"zabka",
        r"dino",
        r"netto",
        r"polo market",
        r"intermarche",
        r"bomi",
        r"delikatesy",
        r"tesco",
        r"frisco",
        r"spar",
        r"piotr i pawel",
        r"piotr.*pawel",
        r"selgros",
        r"makro",
    ],
    "DINING": [
        r"kfc",
        r"mcdonald",
        r"burger king",
        r"subway",
        r"pizza",
        r"kebab",
        r"sushi",
        r"restauracja",
        r"kuchnie swiata",
        r"kuchnie świata",
        r"costa coffee",
        r"starbucks",
        r"coffeeheaven",
        r"marco polo",
        r"smako",
        r"rafal pogon",
        r"bar",
        r"bistro",
        r"caffe",
        r"cafe",
        r"mera kebab",
        r"mleczarnia",
        r"pierogarnia",
        r"karczma",
        r"gospoda",
        r"jadlodajnia",
        r"noodle",
        r"wok",
        r"domino",
        r"telepizza",
        r"papa john",
    ],
    "TRANSPORT": [
        r"koleo",
        r"pkp",
        r"intercity",
        r"flixbus",
        r"polskibus",
        r"unicard",         # City public transport card top-up (Kraków)
        r"smart city",
        r"mpk",
        r"ztm",
        r"uber",
        r"bolt",
        r"free now",
        r"taxi",
        r"paliwo",
        r"orlen",
        r"bp puszcza",
        r"bppuszcza",
        r"shell",
        r"circle k",
        r"lotos",
        r"myjnia",
        r"parking",
        r"autopay",
        r"viamichelin",
        r"autostrady",
        r"gddkia",
        r"kolej",
        r"bilet",
    ],
    "HEALTHCARE": [
        r"apteka",
        r"pharmac",
        r"lux med",
        r"luxmed",
        r"enel-med",
        r"medicover",
        r"centrum medyczne",
        r"szpital",
        r"klinika",
        r"przychodnia",
        r"dentysta",
        r"stomatolog",
        r"optyk",
        r"okulista",
        r"fizjoterapi",
    ],
    "BEAUTY": [
        r"rossmann",
        r"sephora",
        r"douglas",
        r"hebe",
        r"drogeria",
        r"beauty",
        r"fryzjer",
        r"barber",
        r"saloon",
        r"salon",
        r"spa",
        r"kosmetyczka",
        r"nails",
        r"paznokcie",
        r"wax",
        r"depilacja",
    ],
    "CLOTHING": [
        r"reserved",
        r"sinsay",
        r"deichmann",
        r"nanu.?nana",
        r"pepco",
        r"zara",
        r"h&m",
        r"h and m",
        r"cropp",
        r"house",
        r"mohito",
        r"orsay",
        r"diverse",
        r"medicine",
        r"pull.?bear",
        r"bershka",
        r"mango",
        r"vero moda",
        r"medicine",
        r"lamirex",
        r"modivo",
        r"answear",
        r"zalando",
        r"about you",
    ],
    "ENTERTAINMENT": [
        r"hbomax",
        r"netflix",
        r"spotify",
        r"steam",
        r"playstation",
        r"xbox",
        r"epic games",
        r"google play",
        r"apple.?store",
        r"itunes",
        r"cinema",
        r"kinoplex",
        r"multikino",
        r"helios",
        r"teatr",
        r"museum",
        r"muzeum",
        r"galeria",
        r"event",
        r"bilety",
        r"ticketmaster",
        r"going\.",
        r"empik",
        r"matras",
    ],
    "UTILITIES": [
        r"tmobile",
        r"t-mobile",
        r"play",
        r"orange",
        r"plus",
        r"polsat",
        r"netia",
        r"inea",
        r"vectra",
        r"energa",
        r"tauron",
        r"enea",
        r"pge",
        r"gaz",
        r"wodociag",
        r"mpwik",
        r"smiec",
        r"odpad",
        r"internet",
        r"telewizja",
        r"czynsz",
        r"wspólnota",
        r"wspolnota",
    ],
    "RENT": [
        r"^rent$",
        r"rent ",
        r" rent",
        r"czynsz",
        r"najem",
        r"wynajem",
    ],
    "ELECTRONICS": [
        r"euro.?net",
        r"media expert",
        r"media markt",
        r"saturn",
        r"rtv euro",
        r"rtveuro",
        r"neonet",
        r"morele",
        r"al\.?to",
        r"x-kom",
        r"xkom",
        r"komputronik",
        r"apple store",
        r"ispot",
    ],
    "INCOME": [
        r"wynagrodz",
        r"wynagrodzenie",
        r"premia",
        r"bonus",
        r"zwrot.*podatku",
        r"pit.*zwrot",
        r"zfss",
        r"zapomoga",
        r"refundacja",
        r"zwrot",
        r"salary",
        r"income",
    ],
    "TRANSFER": [
        r"transfer to",
        r"transfer from",
        r"przelew",
        r"blik.*(?!unicard)",  # BLIK transfers that aren't transport top-ups
        r"paypal",
        r"paypro",
        r"revolut",
        r"wise",
    ],
    "SUBSCRIPTIONS": [
        r"help\.hbomax",
        r"netflix",
        r"spotify",
        r"amazon prime",
        r"microsoft 365",
        r"adobe",
        r"github",
        r"heroku",
        r"dropbox",
        r"icloud",
        r"google one",
        r"notion",
        r"slack",
    ],
    "HOTEL_TRAVEL": [
        r"booking\.com",
        r"airbnb",
        r"hotel",
        r"hostel",
        r"motel",
        r"apartament",
        r"rentals",
        r"trivago",
        r"expedia",
        r"lot\.com",
        r"ryanair",
        r"wizzair",
        r"airport",
        r"lotnisko",
    ],
}

# Ordered by priority (checked from top to bottom)
# INCOME and RENT are checked first to avoid false positives
CATEGORY_PRIORITY: List[str] = [
    "INCOME",
    "RENT",
    "SUBSCRIPTIONS",
    "TRANSPORT",
    "GROCERIES",
    "DINING",
    "HEALTHCARE",
    "BEAUTY",
    "CLOTHING",
    "ELECTRONICS",
    "ENTERTAINMENT",
    "UTILITIES",
    "HOTEL_TRAVEL",
    "TRANSFER",
    "OTHER",
]

# Human-readable labels for display
CATEGORY_LABELS: Dict[str, str] = {
    "GROCERIES":    "🛒 Groceries",
    "DINING":       "🍽️ Dining & Cafes",
    "TRANSPORT":    "🚌 Transport",
    "HEALTHCARE":   "💊 Healthcare",
    "BEAUTY":       "💄 Beauty & Care",
    "CLOTHING":     "👗 Clothing",
    "ENTERTAINMENT":"🎬 Entertainment",
    "UTILITIES":    "📱 Utilities & Bills",
    "RENT":         "🏠 Rent",
    "ELECTRONICS":  "💻 Electronics",
    "INCOME":       "💰 Income",
    "TRANSFER":     "↔️ Transfer",
    "SUBSCRIPTIONS":"📡 Subscriptions",
    "HOTEL_TRAVEL": "✈️ Travel & Hotels",
    "OTHER":        "❓ Other",
}

# Category color palette for visualizations (hex)
CATEGORY_COLORS: Dict[str, str] = {
    "GROCERIES":    "#2ECC71",
    "DINING":       "#E74C3C",
    "TRANSPORT":    "#3498DB",
    "HEALTHCARE":   "#1ABC9C",
    "BEAUTY":       "#E91E8C",
    "CLOTHING":     "#9B59B6",
    "ENTERTAINMENT":"#F39C12",
    "UTILITIES":    "#95A5A6",
    "RENT":         "#C0392B",
    "ELECTRONICS":  "#2980B9",
    "INCOME":       "#27AE60",
    "TRANSFER":     "#BDC3C7",
    "SUBSCRIPTIONS":"#8E44AD",
    "HOTEL_TRAVEL": "#D35400",
    "OTHER":        "#7F8C8D",
}
